apiVersion: v1
kind: ServiceAccount
metadata:
  name: summit-ksa
  namespace: summit
  annotations:
    iam.gke.io/gcp-service-account: summit-agent@PROJECT_ID.iam.gserviceaccount.com
---
# Bind the Kubernetes service account to the Google service account
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: summit-workload-identity-binding
  namespace: summit
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    external: projects/PROJECT_ID/serviceAccounts/summit-agent@PROJECT_ID.iam.gserviceaccount.com
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:PROJECT_ID.svc.id.goog[summit/summit-ksa] 